import os
import openai
from dotenv import load_dotenv
from random import randint, uniform

# Load environment variables from .env file
load_dotenv()


class Message:
    def __init__(self):
        print(os.getenv("OPENAI_API_KEY"))
        openai.api_key = os.getenv("OPENAI_API_KEY")

    def generate_prompt(self, name, position, company):
        """This function generates a Prompt message with the values
        that it takes

        Args:
            name (str): Name of the person
            position (str): Position of the person
            company (str): Company where currenly work the person

        Returns:
            str: A prompt for the IA
        """
        return f"""Compose a LinkedIn message to {name}, an {position} at {company}, 
                introducing myself as a graduating senior in Computer Science lookinf for any Tranning, entry-level or jr postions for python developer
                on {company}"""

    def message(self, name, position, company):
        """Requests a completion from the OpenAI API based on a prompt generated by the
        `generate_prompt` method using the provided `name`, `position`, and `company`.

        Args:
            name: The name of the person to include in the prompt.
            position: The position of the person to include in the prompt.
            company: The company where the person currently works to include in the prompt.

        Returns:
            A string containing the completion text generated by the OpenAI API.
        """
        self.response = openai.Completion.create(
            model="text-davinci-003",
            prompt=self.generate_prompt(name, position, company),
            temperature=uniform(0.10, 0.70),
            max_tokens=randint(200, 300),
        )
        # Get the completion text from the response
        self.completion_text = self.response.choices[0].text

        # Replace any occurrence  with the actual Values
        self.replacements = {
            "[Your Name]": "Alejandro Cruz",
            "[Name]": "Alejandro Cruz",
            "[Company]": "your Company",
            "[Company Name]": "your Company",
            "[Your Company]": "your Company",
            "[University]": "ITM",
            "[Your University]": "ITM"
        }
        for old, new in self.replacements.items():
            self.completion_text = self.completion_text.replace(old, new)

        return self.completion_text
